import { Component, OnInit } from '@angular/core';
import { DiceUtil } from 'src/app/features/dice/dice-util';
import { ListTable, ListTableRow } from 'src/app/features/tables/list-table';
import { RangeTable, RangeTableRow } from 'src/app/features/tables/range-table';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'app-conjecture',
  templateUrl: './conjecture.component.html',
  styleUrls: ['./conjecture.component.scss']
})
export class ConjectureComponent implements OnInit {
  constructor(
    private dataService: DataService
  ) { }

  ngOnInit(): void { }

  une() {
    const modifier = npcModifier.roll(DiceUtil.rollDiceFormula('1d100').sum);
    const noun = npcNoun.roll(DiceUtil.rollDiceFormula('1d100').sum);
    
    let powerLevel: RangeTableRow | null = null;
    const randomness = sceneRandomness.roll(DiceUtil.rollDiceFormula('1d5').sum);
    if (randomness.value === 'Order') {
      powerLevel = powerLevel_Order.roll(DiceUtil.rollDiceFormula('1d5').sum);
    } else if (randomness.value === 'Calm') {
      powerLevel = powerLevel_Calm.roll(DiceUtil.rollDiceFormula('1d5').sum);
    } else if (randomness.value === 'Standard') {
      powerLevel = powerLevel_Standard.roll(DiceUtil.rollDiceFormula('1d5').sum);
    } else if (randomness.value === 'Disarray') {
      powerLevel = powerLevel_Disarray.roll(DiceUtil.rollDiceFormula('1d5').sum);
    } else if (randomness.value === 'Chaos') {
      powerLevel = powerLevel_Chaos.roll(DiceUtil.rollDiceFormula('1d5').sum);
    }

    const motivationVerb1 = npcMotivationVerb.roll(DiceUtil.rollDiceFormula('1d100').sum);
    const motivationVerb2 = npcMotivationVerb.roll(DiceUtil.rollDiceFormula('1d100').sum);
    const motivationVerb3 = npcMotivationVerb.roll(DiceUtil.rollDiceFormula('1d100').sum);
    const motivationNoun1 = npcMotivationNoun.roll(DiceUtil.rollDiceFormula('1d100').sum);
    const motivationNoun2 = npcMotivationNoun.roll(DiceUtil.rollDiceFormula('1d100').sum);
    const motivationNoun3 = npcMotivationNoun.roll(DiceUtil.rollDiceFormula('1d100').sum);

    this.dataService.data.log.add(`A ${modifier.value} ${noun.value}, ${powerLevel?.value} than the Party. They ${motivationVerb1.value} ${motivationNoun1.value}, ${motivationVerb2.value} ${motivationNoun2.value}, ${motivationVerb3.value} ${motivationNoun3.value}.`);
  }
}

const npcModifier = new ListTable([
  new ListTableRow('Superfluous'),
  new ListTableRow('Addicted'),
  new ListTableRow('Conformist'),
  new ListTableRow('Nefarious'),
  new ListTableRow('Sensible'),
  new ListTableRow('Untrained'),
  new ListTableRow('Romantic'),
  new ListTableRow('Unreasonable'),
  new ListTableRow('Skilled'),
  new ListTableRow('Neglectful'),
  new ListTableRow('Lively'),
  new ListTableRow('Forthright'),
  new ListTableRow('Idealistic'),
  new ListTableRow('Unsupportive'),
  new ListTableRow('Rational'),
  new ListTableRow('Coarse'),
  new ListTableRow('Foolish'),
  new ListTableRow('Cunning'),
  new ListTableRow('Delightful'),
  new ListTableRow('Miserly'),
  new ListTableRow('Inept'),
  new ListTableRow('Banal'),
  new ListTableRow('Logical'),
  new ListTableRow('Subtle'),
  new ListTableRow('Reputable'),
  new ListTableRow('Wicked'),
  new ListTableRow('Lazy'),
  new ListTableRow('Pessimistic'),
  new ListTableRow('Solemn'),
  new ListTableRow('Habitual'),
  new ListTableRow('Meek'),
  new ListTableRow('Helpful'),
  new ListTableRow('Unconcerned'),
  new ListTableRow('Generous'),
  new ListTableRow('Docile'),
  new ListTableRow('Cheery'),
  new ListTableRow('Pragmatic'),
  new ListTableRow('Serene'),
  new ListTableRow('Thoughtful'),
  new ListTableRow('Hopeless'),
  new ListTableRow('Pleasant'),
  new ListTableRow('Insensitive'),
  new ListTableRow('Titled'),
  new ListTableRow('Inexperienced'),
  new ListTableRow('Prying'),
  new ListTableRow('Oblivious'),
  new ListTableRow('Refined'),
  new ListTableRow('Indispensable'),
  new ListTableRow('Scholarly'),
  new ListTableRow('Conservative'),
  new ListTableRow('Uncouth'),
  new ListTableRow('Willful'),
  new ListTableRow('Indifferent'),
  new ListTableRow('Fickle'),
  new ListTableRow('Elderly'),
  new ListTableRow('Sinful'),
  new ListTableRow('Naive'),
  new ListTableRow('Privileged'),
  new ListTableRow('Glum'),
  new ListTableRow('Likable'),
  new ListTableRow('Lethargic'),
  new ListTableRow('Defiant'),
  new ListTableRow('Obnoxious'),
  new ListTableRow('Insightful'),
  new ListTableRow('Tactless'),
  new ListTableRow('Fanatic'),
  new ListTableRow('Plebeian'),
  new ListTableRow('Childish'),
  new ListTableRow('Pious'),
  new ListTableRow('Uneducated'),
  new ListTableRow('Inconsiderate'),
  new ListTableRow('Cultured'),
  new ListTableRow('Revolting'),
  new ListTableRow('Curious'),
  new ListTableRow('Touchy'),
  new ListTableRow('Needy'),
  new ListTableRow('Dignified'),
  new ListTableRow('Pushy'),
  new ListTableRow('Kind'),
  new ListTableRow('Corrupt'),
  new ListTableRow('Jovial'),
  new ListTableRow('Shrewd'),
  new ListTableRow('Liberal'),
  new ListTableRow('Compliant'),
  new ListTableRow('Destitute'),
  new ListTableRow('Conniving'),
  new ListTableRow('Careful'),
  new ListTableRow('Alluring'),
  new ListTableRow('Defective'),
  new ListTableRow('Optimistic'),
  new ListTableRow('Affluent'),
  new ListTableRow('Despondent'),
  new ListTableRow('Mindless'),
  new ListTableRow('Passionate'),
  new ListTableRow('Devoted'),
  new ListTableRow('Established'),
  new ListTableRow('Unseemly'),
  new ListTableRow('Dependable'),
  new ListTableRow('Righteous'),
  new ListTableRow('Confident'),
]);
const npcNoun = new ListTable([
  new ListTableRow('Gypsy'),
  new ListTableRow('Witch'),
  new ListTableRow('Merchant'),
  new ListTableRow('Expert'),
  new ListTableRow('Commoner'),
  new ListTableRow('Judge'),
  new ListTableRow('Ranger'),
  new ListTableRow('Occultist'),
  new ListTableRow('Reverend'),
  new ListTableRow('Thug'),
  new ListTableRow('Drifter'),
  new ListTableRow('Journeyman'),
  new ListTableRow('Statesman'),
  new ListTableRow('Astrologer'),
  new ListTableRow('Duelist'),
  new ListTableRow('Jack-of-all-trades'),
  new ListTableRow('Aristocrat'),
  new ListTableRow('Preacher'),
  new ListTableRow('Artisan'),
  new ListTableRow('Rogue'),
  new ListTableRow('Missionary'),
  new ListTableRow('Outcast'),
  new ListTableRow('Mercenary'),
  new ListTableRow('Caretaker'),
  new ListTableRow('Hermit'),
  new ListTableRow('Orator'),
  new ListTableRow('Chieftain'),
  new ListTableRow('Pioneer'),
  new ListTableRow('Burglar'),
  new ListTableRow('Vicar'),
  new ListTableRow('Officer'),
  new ListTableRow('Explorer'),
  new ListTableRow('Warden'),
  new ListTableRow('Outlaw'),
  new ListTableRow('Adept'),
  new ListTableRow('Bum'),
  new ListTableRow('Sorcerer'),
  new ListTableRow('Laborer'),
  new ListTableRow('Master'),
  new ListTableRow('Ascendant'),
  new ListTableRow('Villager'),
  new ListTableRow('Magus'),
  new ListTableRow('Conscript'),
  new ListTableRow('Worker'),
  new ListTableRow('Actor'),
  new ListTableRow('Herald'),
  new ListTableRow('Highwayman'),
  new ListTableRow('Fortune-hunter'),
  new ListTableRow('Governor'),
  new ListTableRow('Scrapper'),
  new ListTableRow('Monk'),
  new ListTableRow('Homemaker'),
  new ListTableRow('Recluse'),
  new ListTableRow('Steward'),
  new ListTableRow('Polymath'),
  new ListTableRow('Magician'),
  new ListTableRow('Traveler'),
  new ListTableRow('Vagrant'),
  new ListTableRow('Apprentice'),
  new ListTableRow('Politician'),
  new ListTableRow('Mediator'),
  new ListTableRow('Crook'),
  new ListTableRow('Civilian'),
  new ListTableRow('Activist'),
  new ListTableRow('Hero'),
  new ListTableRow('Champion'),
  new ListTableRow('Cleric'),
  new ListTableRow('Slave'),
  new ListTableRow('Gunman'),
  new ListTableRow('Clairvoyant'),
  new ListTableRow('Patriarch'),
  new ListTableRow('Shopkeeper'),
  new ListTableRow('Crone'),
  new ListTableRow('Adventurer'),
  new ListTableRow('Soldier'),
  new ListTableRow('Entertainer'),
  new ListTableRow('Craftsman'),
  new ListTableRow('Scientist'),
  new ListTableRow('Ascetic'),
  new ListTableRow('Superior'),
  new ListTableRow('Performer'),
  new ListTableRow('Magister'),
  new ListTableRow('Serf'),
  new ListTableRow('Brute'),
  new ListTableRow('Inquisitor'),
  new ListTableRow('Lord'),
  new ListTableRow('Villain'),
  new ListTableRow('Professor'),
  new ListTableRow('Servant'),
  new ListTableRow('Charmer'),
  new ListTableRow('Globetrotter'),
  new ListTableRow('Sniper'),
  new ListTableRow('Courtier'),
  new ListTableRow('Priest'),
  new ListTableRow('Tradesman'),
  new ListTableRow('Hitman'),
  new ListTableRow('Wizard'),
  new ListTableRow('Beggar'),
  new ListTableRow('Tradesman'),
  new ListTableRow('Warrior'),
]);
const sceneRandomness = new ListTable([
  new ListTableRow('Order'),
  new ListTableRow('Calm'),
  new ListTableRow('Standard'),
  new ListTableRow('Disarray'),
  new ListTableRow('Chaos'),
]);
const powerLevel_Order = new RangeTable([
  new RangeTableRow(1, 2, 'Much Weaker'),
  new RangeTableRow(3, 10, 'Slightly Weaker'),
  new RangeTableRow(11, 90, 'Comparable'),
  new RangeTableRow(91, 98, 'Slightly Stronger'),
  new RangeTableRow(99, 100, 'Much Stronger'),
]);
const powerLevel_Calm = new RangeTable([
  new RangeTableRow(1, 4, 'Much Weaker'),
  new RangeTableRow(5, 15, 'Slightly Weaker'),
  new RangeTableRow(16, 85, 'Comparable'),
  new RangeTableRow(86, 96, 'Slightly Stronger'),
  new RangeTableRow(97, 100, 'Much Stronger'),
]);
const powerLevel_Standard = new RangeTable([
  new RangeTableRow(1, 5, 'Much Weaker'),
  new RangeTableRow(6, 20, 'Slightly Weaker'),
  new RangeTableRow(21, 80, 'Comparable'),
  new RangeTableRow(81, 95, 'Slightly Stronger'),
  new RangeTableRow(96, 100, 'Much Stronger'),
]);
const powerLevel_Disarray = new RangeTable([
  new RangeTableRow(1, 8, 'Much Weaker'),
  new RangeTableRow(9, 25, 'Slightly Weaker'),
  new RangeTableRow(26, 75, 'Comparable'),
  new RangeTableRow(76, 92, 'Slightly Stronger'),
  new RangeTableRow(93, 100, 'Much Stronger'),
]);
const powerLevel_Chaos = new RangeTable([
  new RangeTableRow(1, 12, 'Much Weaker'),
  new RangeTableRow(13, 30, 'Slightly Weaker'),
  new RangeTableRow(31, 70, 'Comparable'),
  new RangeTableRow(71, 88, 'Slightly Stronger'),
  new RangeTableRow(89, 100, 'Much Stronger'),
]);
const npcMotivationVerb = new ListTable([
  new ListTableRow('Advise'),
  new ListTableRow('Obtain'),
  new ListTableRow('Attempt'),
  new ListTableRow('Spoil'),
  new ListTableRow('Oppress'),
  new ListTableRow('Interact'),
  new ListTableRow('Create'),
  new ListTableRow('Abduct'),
  new ListTableRow('Promote'),
  new ListTableRow('Conceive'),
  new ListTableRow('Blight'),
  new ListTableRow('Progress'),
  new ListTableRow('Distress'),
  new ListTableRow('Possess'),
  new ListTableRow('Record'),
  new ListTableRow('Embrace'),
  new ListTableRow('Contact'),
  new ListTableRow('Pursue'),
  new ListTableRow('Associate'),
  new ListTableRow('Prepare'),
  new ListTableRow('Shepherd'),
  new ListTableRow('Abuse'),
  new ListTableRow('Indulge'),
  new ListTableRow('Chronicle'),
  new ListTableRow('Fulfill'),
  new ListTableRow('Drive'),
  new ListTableRow('Review'),
  new ListTableRow('Aid'),
  new ListTableRow('Follow'),
  new ListTableRow('Advance'),
  new ListTableRow('Guard'),
  new ListTableRow('Conquer'),
  new ListTableRow('Hinder'),
  new ListTableRow('Plunder'),
  new ListTableRow('Construct'),
  new ListTableRow('Encourage'),
  new ListTableRow('Agonize'),
  new ListTableRow('Comprehend'),
  new ListTableRow('Administer'),
  new ListTableRow('Relate'),
  new ListTableRow('Take'),
  new ListTableRow('Discover'),
  new ListTableRow('Deter'),
  new ListTableRow('Acquire'),
  new ListTableRow('Damage'),
  new ListTableRow('Publicize'),
  new ListTableRow('Burden'),
  new ListTableRow('Advocate'),
  new ListTableRow('Implement'),
  new ListTableRow('Understand'),
  new ListTableRow('Collaborate'),
  new ListTableRow('Strive'),
  new ListTableRow('Complete'),
  new ListTableRow('Compel'),
  new ListTableRow('Join'),
  new ListTableRow('Assist'),
  new ListTableRow('Defile'),
  new ListTableRow('Produce'),
  new ListTableRow('Institute'),
  new ListTableRow('Account'),
  new ListTableRow('Work'),
  new ListTableRow('Accompany'),
  new ListTableRow('Offend'),
  new ListTableRow('Guide'),
  new ListTableRow('Learn'),
  new ListTableRow('Persecute'),
  new ListTableRow('Communicate'),
  new ListTableRow('Process'),
  new ListTableRow('Report'),
  new ListTableRow('Develop'),
  new ListTableRow('Steal'),
  new ListTableRow('Suggest'),
  new ListTableRow('Weaken'),
  new ListTableRow('Achieve'),
  new ListTableRow('Secure'),
  new ListTableRow('Inform'),
  new ListTableRow('Patronize'),
  new ListTableRow('Depress'),
  new ListTableRow('Determine'),
  new ListTableRow('Seek'),
  new ListTableRow('Manage'),
  new ListTableRow('Suppress'),
  new ListTableRow('Proclaim'),
  new ListTableRow('Operate'),
  new ListTableRow('Access'),
  new ListTableRow('Refine'),
  new ListTableRow('Compose'),
  new ListTableRow('Undermine'),
  new ListTableRow('Explain'),
  new ListTableRow('Discourage'),
  new ListTableRow('Attend'),
  new ListTableRow('Detect'),
  new ListTableRow('Execute'),
  new ListTableRow('Maintain'),
  new ListTableRow('Realize'),
  new ListTableRow('Convey'),
  new ListTableRow('Rob'),
  new ListTableRow('Establish'),
  new ListTableRow('Overthrow'),
  new ListTableRow('Support'),
]);
const npcMotivationNoun = new ListTable([
  new ListTableRow('Wealth'),
  new ListTableRow('Hardship'),
  new ListTableRow('Affluence'),
  new ListTableRow('Resources'),
  new ListTableRow('Prosperity'),
  new ListTableRow('Poverty'),
  new ListTableRow('Opulence'),
  new ListTableRow('Deprivation'),
  new ListTableRow('Success'),
  new ListTableRow('Distress'),
  new ListTableRow('Contraband'),
  new ListTableRow('Music'),
  new ListTableRow('Literature'),
  new ListTableRow('Technology'),
  new ListTableRow('Alcohol'),
  new ListTableRow('Medicines'),
  new ListTableRow('Beauty'),
  new ListTableRow('Strength'),
  new ListTableRow('Intelligence'),
  new ListTableRow('Force'),
  new ListTableRow('The wealthy'),
  new ListTableRow('The populous'),
  new ListTableRow('Enemies'),
  new ListTableRow('The public'),
  new ListTableRow('Religion'),
  new ListTableRow('The poor'),
  new ListTableRow('Family'),
  new ListTableRow('The elite'),
  new ListTableRow('Academia'),
  new ListTableRow('The forsaken'),
  new ListTableRow('The law'),
  new ListTableRow('The government'),
  new ListTableRow('The oppressed'),
  new ListTableRow('Friends'),
  new ListTableRow('Criminals'),
  new ListTableRow('Allies'),
  new ListTableRow('Secret societies'),
  new ListTableRow('The world'),
  new ListTableRow('Military'),
  new ListTableRow('The church'),
  new ListTableRow('Dreams'),
  new ListTableRow('Discretion'),
  new ListTableRow('Love'),
  new ListTableRow('Freedom'),
  new ListTableRow('Pain'),
  new ListTableRow('Faith'),
  new ListTableRow('Slavery'),
  new ListTableRow('Enlightenment'),
  new ListTableRow('Racism'),
  new ListTableRow('Sensuality'),
  new ListTableRow('Dissonance'),
  new ListTableRow('Peace'),
  new ListTableRow('Discrimination'),
  new ListTableRow('Disbelief'),
  new ListTableRow('Pleasure'),
  new ListTableRow('Hate'),
  new ListTableRow('Happiness'),
  new ListTableRow('Servitude'),
  new ListTableRow('Harmony'),
  new ListTableRow('Justice'),
  new ListTableRow('Gluttony'),
  new ListTableRow('Lust'),
  new ListTableRow('Envy'),
  new ListTableRow('Greed'),
  new ListTableRow('Laziness'),
  new ListTableRow('Wrath'),
  new ListTableRow('Pride'),
  new ListTableRow('Purity'),
  new ListTableRow('Moderation'),
  new ListTableRow('Vigilance'),
  new ListTableRow('Zeal'),
  new ListTableRow('Composure'),
  new ListTableRow('Charity'),
  new ListTableRow('Modesty'),
  new ListTableRow('Atrocities'),
  new ListTableRow('Cowardice'),
  new ListTableRow('Narcissism'),
  new ListTableRow('Compassion'),
  new ListTableRow('Valor'),
  new ListTableRow('Patience'),
  new ListTableRow('Advice'),
  new ListTableRow('Propaganda'),
  new ListTableRow('Science'),
  new ListTableRow('Knowledge'),
  new ListTableRow('Communications'),
  new ListTableRow('Lies'),
  new ListTableRow('Myths'),
  new ListTableRow('Riddles'),
  new ListTableRow('Stories'),
  new ListTableRow('Legends'),
  new ListTableRow('Industry'),
  new ListTableRow('New religions'),
  new ListTableRow('Progress'),
  new ListTableRow('Animals'),
  new ListTableRow('Ghosts'),
  new ListTableRow('Magic'),
  new ListTableRow('Nature'),
  new ListTableRow('Old religions'),
  new ListTableRow('Expertise'),
  new ListTableRow('Spirits'),
]);